x-common-infos:
  # Env variables stored in a .env file at same level than docker-compose.yaml
  environment: &common-env
    POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME:-postgres_bloom}
    POSTGRES_DB: ${POSTGRES_DB:-bloom_db}
    POSTGRES_USER: ${POSTGRES_USER:-bloom_user}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bloom}
    LOGGING_LEVEL: ${LOGGING_LEVEL:-INFO}

services:
  bloom-backend:
    command: bash -c "echo 'Development mode. Launching interractive bash'; bash"
    tty: true
    stdin_open: true

  bloom-frontend:
    command: bash -c "echo 'Development mode. Launching interractive bash'; bash"
    tty: true
    stdin_open: true

  #bloom-init:
  #  command: bash
  #  tty: true
  #  stdin_open: true

networks:
  bloom_net:
    name: bloom_net
