version: "3.7"
services:
  postgres:
    container_name: postgres_bloom
    environment:
      HOSTNAME: ${POSTGRES_HOSTNAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgis/postgis:14-3.3-alpine
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
        - bloom_net
    restart: unless-stopped

  pgadmin:
      container_name: pgadmin_bloom
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@dev.com}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-dev}
      volumes:
        - ./pgpassfile:/pgadmin4/pgpassfile
        - ./pgadmin-servers.json:/pgadmin4/servers.json
      ports:
        - "${PGADMIN_PORT:-5080}:80"
      networks:
        - bloom_net
      restart: unless-stopped

networks:
  bloom_net:
    name: bloom_net