version: "3.7"
services:
  postgres:
    container_name: ${POSTGRES_HOSTNAME:-postgres_bloom}-test
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
        - bloom_net
    restart: unless-stopped

  app:
      container_name: app_bloom-test
      hostname: app_bloom
      build:
        context: ..
        dockerfile: docker-env/Dockerfile
        args:
            APP_ENV: test
      environment:
        APP_ENV: test

networks:
  bloom_net:
    name: bloom_net