name: version supports

on:
  pull_request:
  push:
    branches: [main]

jobs:
  install_python_0308:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Test App installation in python 3.8
      run: |
        poetry install
  install_python_0309:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Test App installation in python 3.9
      run: |
        poetry install
  install_python_0310:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Test App installation in python 3.10
      run: |
        poetry install
  install_python_0311:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Test App installation in python 3.11
      run: |
        poetry install
  install_python_0312:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Test App installation in python 3.12
      run: |
        poetry install
